insert into Clients (Second_Name, First_Name, Last_Name, Email, Phone) values ('Andronov', 'Ilya', 'Alexeevich', 'har1zma@gmail.com', '+793022030555')
insert into Tariffs (name, description, price) values ('AllIn', 'Well be AllIn', 1000)
insert into Services (name, description, price) values ('Баня', 'Будет баня', 300)
insert into Services (name, description, price) values ('НеБаня', 'Будет небаня', 350)
insert into Facilities (name) values ('Телевизор')
insert into Facilities (name) values ('НеТелевизор')
insert into Apartaments (number, area, photo_path, reservation, tariffs_id) values (1, 35, '404', 1, 1)
insert into apartaments_facilities (apartaments_id, facilities_id) values (1, 1)
insert into apartaments_facilities (apartaments_id, facilities_id) values (1, 2)
insert into apartaments_services (apartaments_id, services_id) values (1, 1)
insert into apartaments_services (apartaments_id, services_id) values (1, 2)
