insert into Clients (Second_Name, First_Name, Last_Name, Email, Phone) values ('Андронов', 'Илья', 'Алексеевич', 'har1zma@gmail.com', '+79302203055')
insert into Tariffs (name, description, price) values ('AllIn', 'Well be AllIn', 1000)
insert into Tariffs (name, description, price) values ('HalfAllIn', 'Well be HalfAllIn', 700)
insert into Services (name, description, price) values ('Баня', 'Баня при отеле', 300)
insert into Services (name, description, price) values ('Массаж', 'Расслабляющий массаж', 350)
insert into Facilities (name) values ('Телевизор')
insert into Facilities (name) values ('Фен')
insert into Facilities (name) values ('Wi-Fi')
insert into Apartaments (number, area, photo_path, reservation, tariffs_id) values (1, 35, 'testImage.jpg', 1, 1)
insert into Apartaments (number, area, photo_path, reservation, tariffs_id) values (2, 50, '404', 1, 2)
insert into apartaments_facilities (apartaments_id, facilities_id) values (1, 1)
insert into apartaments_facilities (apartaments_id, facilities_id) values (1, 2)
insert into apartaments_services (apartaments_id, services_id) values (1, 1)
insert into apartaments_services (apartaments_id, services_id) values (1, 2)
insert into Clients (Second_Name, First_Name, Last_Name, Email, Phone) values ('Лука', 'Руслан', 'Олегович', 'lukasus@mail.com', '+79341432424')
insert into Clients (Second_Name, First_Name, Last_Name, Email, Phone) values ('Орехов', 'Андрей', 'Алексеевич', 'didjeyokey@gmail.com', '+79303533135')
insert into Clients (Second_Name, First_Name, Last_Name, Email, Phone) values ('Вингорадов', 'Илья', 'Алексеевич', 'vinogradow.com', '+79302203055')
insert into Bookings (clients_id, start_time, end_time, is_active, apartaments_id) values (1, '2023-12-03', '2023-12-05', 1, 1)
insert into Bookings (clients_id, start_time, end_time, is_active, apartaments_id) values (2, '2023-11-04', '2023-12-01', 1, 2)
insert into Bookings (clients_id, start_time, end_time, is_active, apartaments_id) values (2, '2023-12-06', '2023-12-08', 1, 2)
insert into bookings_services (bookings_id, services_id) values (1, 1)
insert into bookings_services (bookings_id, services_id) values (1, 2)


